REGISTER Pelanggan
POST http://localhost:3000/api/pelanggan/register
Content-Type: application/json
Accept: application/json

{
  "email": "Heru@example.com",
  "password" : "Herupurnomo17.",
  "nama" : "Heru Purnomo"
}

{
    "email": "Ellen@example.com",
    "password": "EllenAngelina.",
    "nama": "Ellen Angelina"
}

LOGIN Pelanggan
POST http://localhost:3000/api/pelanggan/login
Content-Type: application/json
Accept: application/json

{
  "email": "Heru@example.com",
  "password" : "Herupurnomo17."
}
token: 1f2c79f8-40ce-40e2-86f4-8b29bc8704ba

{
  "email": "Ellen@example.com",
  "password" : "EllenAngelina."
}
token: d900ac24-e76b-4a7a-90ef-739930de026e

LOGOUT
DELETE http://localhost:3000/api/pelanggan/logout
Content-Type: application/json
Accept: application/json
Authorization: 85b65db9-217e-4470-b398-66504a0c98ba

{
  "email": "heru@example.com"
}

REGISTER Admin
POST http://localhost:3000/api/admin/register
Content-Type: application/json
Accept: application/json

{
  "username": "admin_heru",
  "password" : "Herupurnomo17."
}

LOGIN admin
POST http://localhost:3000/api/admin/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin_heru",
  "password" : "Herupurnomo17."
}

 "token": "dbe5f306-521f-4fb5-acfb-be03d2df8fb8"

LOGOUT
DELETE http://localhost:3000/api/admin/logout
Content-Type: application/json
Accept: application/json
Authorization: 85b65db9-217e-4470-b398-66504a0c98ba

### GET semua produk
GET http://localhost:3000/api/produk
Accept: application/json

###

### GET produk dengan search, kategori, paginasi
GET http://localhost:3000/api/produk?search=plat&kategori=201&page=1&limit=5
Accept: application/json

###

### GET produk berdasarkan ID
GET http://localhost:3000/api/produk/PASTE_PRODUK_ID_DI_SINI
Accept: application/json

###

### POST tambah produk baru
POST http://localhost:3000/api/produk
Content-Type: application/json
Accept: application/json

{
  "namaProduk": "Produk 1",
  "kategori": "304",
  "harga": 230000,
  "stok": 50,
  "thickness": [1, 2, 3],
  "hole": [],
  "size": ["1x2", "2x4"],
  "gambar": "https://ik.imagekit.io/6iomykfjj/upload-dasar/perforated-1748664027616_w6V4kyHTI.jpg"
}

{
  "namaProduk": "Produk 2",
  "kategori": "304",
  "harga": 230000,
  "stok": 50,
  "thickness": [1, 2, 3],
  "hole": [],
  "size": ["1x2", "2x4"],
  "gambar": "https://ik.imagekit.io/6iomykfjj/upload-dasar/perforated_2-1748664044863_velzuwQSs.jpg"
}

{
  "namaProduk": "Produk 3",
  "kategori": "304",
  "harga": 230000,
  "stok": 50,
  "thickness": [1, 2, 3],
  "hole": [],
  "size": ["1x2", "2x4"],
  "gambar": "https://ik.imagekit.io/6iomykfjj/upload-dasar/hollow-1748664190535_yz7LRUEs1.jpg"
}

{
  "namaProduk": "Produk 4",
  "kategori": "304",
  "harga": 230000,
  "stok": 50,
  "thickness": [1, 2, 3],
  "hole": [],
  "size": ["1x2", "2x4"],
  "gambar": "https://ik.imagekit.io/6iomykfjj/upload-dasar/hero-1748664204167__drPCD12H.jpg"
}

{
  "namaProduk": "Produk 5",
  "kategori": "304",
  "harga": 230000,
  "stok": 50,
  "thickness": [1, 2, 3],
  "hole": [],
  "size": ["1x2", "2x4"],
  "gambar": "https://ik.imagekit.io/6iomykfjj/upload-dasar/angle-1748664219218_FhBQmvbL1.jpg"
}

###

### PUT update produk berdasarkan ID
PUT http://localhost:3000/api/produk/PASTE_PRODUK_ID_DI_SINI
Content-Type: application/json
Accept: application/json

{
  "namaProduk": "PLAT STAINLESS AISI 304 - Edited",
  "kategori": "304",
  "harga": 250000,
  "stok": 40,
  "thickness": [1, 2, 3],
  "hole": [],
  "size": ["1x2", "2x4"],
  "gambar": "https://example.com/plat304.jpg"
}

###

### DELETE produk
DELETE http://localhost:3000/api/produk/PASTE_PRODUK_ID_DI_SINI
Accept: application/json


### Ambil semua keranjang milik pelanggan tertentu (pelanggan atau admin)
GET http://localhost:3000/api/keranjang/64fabc1234567890abc12345
Authorization: Bearer <TOKEN_PELANGGAN>


### Ambil item keranjang berdasarkan ID (pelanggan atau admin)
GET http://localhost:3000/api/keranjang/item/64fa22223333abcdeeff1111
Authorization: Bearer <TOKEN_ADMIN>


### Tambah item ke keranjang (hanya pelanggan)
POST http://localhost:3000/api/keranjang
Authorization: Bearer <TOKEN_PELANGGAN>
Content-Type: application/json

{
  "userId": "64fabc1234567890abc12345",
  "produkId": "64fa99998888abcdef12345",
  "jumlah": 2,
  "size": "2x4",
  "thickness": 1.5,
  "hole": 5
}


### Update jumlah item keranjang (hanya pelanggan)
PATCH http://localhost:3000/api/keranjang/64fa22223333abcdeeff1111/jumlah
Authorization: Bearer <TOKEN_PELANGGAN>
Content-Type: application/json

{
  "jumlah": 3
}


### Update spesifikasi item keranjang (hanya pelanggan)
PATCH http://localhost:3000/api/keranjang/64fa22223333abcdeeff1111/spesifikasi
Authorization: Bearer <TOKEN_PELANGGAN>
Content-Type: application/json

{
  "size": "1x2",
  "thickness": 2.0,
  "hole": 4,
  "jumlah": 1
}


### Hapus item keranjang (hanya pelanggan)
DELETE http://localhost:3000/api/keranjang/64fa22223333abcdeeff1111
Authorization: Bearer <TOKEN_PELANGGAN>
