### REGISTER Pelanggan
POST http://localhost:5001/api/pelanggan/register
Content-Type: application/json
Accept: application/json

{
  "email": "Heru@example.com",
  "password" : "Herupurnomo17.",
  "nama" : "Heru Purnomo"
}

###
{
    "email": "Ellen@example.com",
    "password": "EllenAngelina.",
    "nama": "Ellen Angelina"
}

### LOGIN Pelanggan
POST http://localhost:5001/api/pelanggan/login
Content-Type: application/json
Accept: application/json

{
  "email": "Heru@example.com",
  "password" : "Herupurnomo17."
}
# token: 1f2c79f8-40ce-40e2-86f4-8b29bc8704ba

###
{
  "email": "Ellen@example.com",
  "password" : "EllenAngelina."
}
# token: d900ac24-e76b-4a7a-90ef-739930de026e

### LOGOUT
DELETE http://localhost:5001/api/pelanggan/logout
Content-Type: application/json
Accept: application/json
Authorization: 85b65db9-217e-4470-b398-66504a0c98ba

{
  "email": "heru@example.com"
}